/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Fri Jun  2 20:26:00 PDT 2017
 * 
 */

/* Generation options: */
#ifndef __mkIFFTFolded_h__
#define __mkIFFTFolded_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkIFFTFolded module */
class MOD_mkIFFTFolded : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_bfly_0;
  MOD_mkBfly4 INST_bfly_1;
  MOD_mkBfly4 INST_bfly_10;
  MOD_mkBfly4 INST_bfly_11;
  MOD_mkBfly4 INST_bfly_12;
  MOD_mkBfly4 INST_bfly_13;
  MOD_mkBfly4 INST_bfly_14;
  MOD_mkBfly4 INST_bfly_15;
  MOD_mkBfly4 INST_bfly_2;
  MOD_mkBfly4 INST_bfly_3;
  MOD_mkBfly4 INST_bfly_4;
  MOD_mkBfly4 INST_bfly_5;
  MOD_mkBfly4 INST_bfly_6;
  MOD_mkBfly4 INST_bfly_7;
  MOD_mkBfly4 INST_bfly_8;
  MOD_mkBfly4 INST_bfly_9;
  MOD_Reg<tUInt8> INST_counter;
  MOD_Fifo<tUWide> INST_f1;
  MOD_Fifo<tUWide> INST_f2;
  MOD_Fifo<tUWide> INST_f3;
  MOD_Fifo<tUWide> INST_inFIFO;
  MOD_Fifo<tUWide> INST_outFIFO;
 
 /* Constructor */
 public:
  MOD_mkIFFTFolded(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_x__h120067;
 
 /* Local definitions */
 private:
  tUInt8 DEF_x__h88334;
  tUWide DEF_f3_first____d590;
  tUWide DEF_f2_first____d456;
  tUWide DEF_f1_first____d322;
  tUWide DEF_inFIFO_first____d22;
  tUInt64 DEF__63_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_0_CONCAT_ETC___d21;
  tUInt64 DEF__59_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_8_CONCAT_ETC___d38;
  tUInt64 DEF__55_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_4_CONCAT_ETC___d54;
  tUInt64 DEF__51_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_0_CONCAT_ETC___d70;
  tUInt64 DEF__47_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_6_CONCAT_ETC___d86;
  tUInt64 DEF__43_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_2_CONCAT_ETC___d102;
  tUInt64 DEF__39_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_08_CONCA_ETC___d118;
  tUInt64 DEF__35_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_24_CONCA_ETC___d134;
  tUInt64 DEF__31_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_40_CONCA_ETC___d150;
  tUInt64 DEF__27_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_56_CONCA_ETC___d166;
  tUInt64 DEF__23_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_72_CONCA_ETC___d182;
  tUInt64 DEF__19_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_88_CONCA_ETC___d198;
  tUInt64 DEF__15_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_04_CONCA_ETC___d214;
  tUInt64 DEF__11_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_20_CONCA_ETC___d230;
  tUInt64 DEF__7_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_36_CONCAT_ETC___d246;
  tUInt64 DEF__3_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_52_CONCAT_ETC___d262;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d584;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d581;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d315;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d312;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d450;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d447;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d578;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d309;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d444;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d575;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d306;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d441;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d572;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d303;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d438;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d569;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d300;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d435;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d566;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d297;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d432;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d563;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d294;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d429;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d560;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d291;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d426;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d557;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d288;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d423;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d554;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d285;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d420;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d551;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d282;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d417;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d548;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d279;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d414;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d545;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d276;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d411;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d542;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d273;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d408;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d539;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d270;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d405;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d536;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d267;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d402;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d531;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d251;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d397;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d526;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d235;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d392;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d521;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d219;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d387;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d516;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d203;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d382;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d511;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d187;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d377;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d506;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d171;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d372;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d501;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d155;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d367;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d496;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d139;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d362;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d491;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d123;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d357;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d486;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d107;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d352;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d481;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d91;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d347;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d476;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d75;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d342;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d471;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d59;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d337;
  tUInt8 DEF_x__h116291;
  tUInt8 DEF_x__h116341;
  tUInt8 DEF_x__h114530;
  tUInt8 DEF_x__h114580;
  tUInt8 DEF_x__h112769;
  tUInt8 DEF_x__h112819;
  tUInt8 DEF_x__h111008;
  tUInt8 DEF_x__h111058;
  tUInt8 DEF_x__h109247;
  tUInt8 DEF_x__h109297;
  tUInt8 DEF_x__h107486;
  tUInt8 DEF_x__h107536;
  tUInt8 DEF_x__h105725;
  tUInt8 DEF_x__h105775;
  tUInt8 DEF_x__h103964;
  tUInt8 DEF_x__h104014;
  tUInt8 DEF_x__h102203;
  tUInt8 DEF_x__h102253;
  tUInt8 DEF_x__h100442;
  tUInt8 DEF_x__h100492;
  tUInt8 DEF_x__h98681;
  tUInt8 DEF_x__h98731;
  tUInt8 DEF_x__h96920;
  tUInt8 DEF_x__h96970;
  tUInt8 DEF_x__h95159;
  tUInt8 DEF_x__h95209;
  tUInt8 DEF_x__h93398;
  tUInt8 DEF_x__h93448;
  tUInt8 DEF_x__h91637;
  tUInt8 DEF_x__h91687;
  tUInt8 DEF_x__h88516;
  tUInt8 DEF_x__h88566;
  tUInt8 DEF_x__h115787;
  tUInt8 DEF_x__h116068;
  tUInt8 DEF_x__h116109;
  tUInt8 DEF_x__h116159;
  tUInt8 DEF_x__h114026;
  tUInt8 DEF_x__h114307;
  tUInt8 DEF_x__h114348;
  tUInt8 DEF_x__h114398;
  tUInt8 DEF_x__h112265;
  tUInt8 DEF_x__h112546;
  tUInt8 DEF_x__h112587;
  tUInt8 DEF_x__h112637;
  tUInt8 DEF_x__h110504;
  tUInt8 DEF_x__h110785;
  tUInt8 DEF_x__h110826;
  tUInt8 DEF_x__h110876;
  tUInt8 DEF_x__h108743;
  tUInt8 DEF_x__h109024;
  tUInt8 DEF_x__h109065;
  tUInt8 DEF_x__h109115;
  tUInt8 DEF_x__h106982;
  tUInt8 DEF_x__h107263;
  tUInt8 DEF_x__h107304;
  tUInt8 DEF_x__h107354;
  tUInt8 DEF_x__h105221;
  tUInt8 DEF_x__h105502;
  tUInt8 DEF_x__h105543;
  tUInt8 DEF_x__h105593;
  tUInt8 DEF_x__h103460;
  tUInt8 DEF_x__h103741;
  tUInt8 DEF_x__h103782;
  tUInt8 DEF_x__h103832;
  tUInt8 DEF_x__h101699;
  tUInt8 DEF_x__h101980;
  tUInt8 DEF_x__h102021;
  tUInt8 DEF_x__h102071;
  tUInt8 DEF_x__h99938;
  tUInt8 DEF_x__h100219;
  tUInt8 DEF_x__h100260;
  tUInt8 DEF_x__h100310;
  tUInt8 DEF_x__h98177;
  tUInt8 DEF_x__h98458;
  tUInt8 DEF_x__h98499;
  tUInt8 DEF_x__h98549;
  tUInt8 DEF_x__h96416;
  tUInt8 DEF_x__h96697;
  tUInt8 DEF_x__h96738;
  tUInt8 DEF_x__h96788;
  tUInt8 DEF_x__h94655;
  tUInt8 DEF_x__h94936;
  tUInt8 DEF_x__h94977;
  tUInt8 DEF_x__h95027;
  tUInt8 DEF_x__h92894;
  tUInt8 DEF_x__h93175;
  tUInt8 DEF_x__h93216;
  tUInt8 DEF_x__h93266;
  tUInt8 DEF_x__h91133;
  tUInt8 DEF_x__h91414;
  tUInt8 DEF_x__h91455;
  tUInt8 DEF_x__h91505;
  tUInt8 DEF_x__h88012;
  tUInt8 DEF_x__h88293;
  tUInt8 DEF_x__h88384;
  tUInt8 DEF_x__h116200;
  tUInt8 DEF_x__h116250;
  tUInt8 DEF_x__h114439;
  tUInt8 DEF_x__h114489;
  tUInt8 DEF_x__h112678;
  tUInt8 DEF_x__h112728;
  tUInt8 DEF_x__h110917;
  tUInt8 DEF_x__h110967;
  tUInt8 DEF_x__h109156;
  tUInt8 DEF_x__h109206;
  tUInt8 DEF_x__h107395;
  tUInt8 DEF_x__h107445;
  tUInt8 DEF_x__h105634;
  tUInt8 DEF_x__h105684;
  tUInt8 DEF_x__h103873;
  tUInt8 DEF_x__h103923;
  tUInt8 DEF_x__h102112;
  tUInt8 DEF_x__h102162;
  tUInt8 DEF_x__h100351;
  tUInt8 DEF_x__h100401;
  tUInt8 DEF_x__h98590;
  tUInt8 DEF_x__h98640;
  tUInt8 DEF_x__h96829;
  tUInt8 DEF_x__h96879;
  tUInt8 DEF_x__h95068;
  tUInt8 DEF_x__h95118;
  tUInt8 DEF_x__h93307;
  tUInt8 DEF_x__h93357;
  tUInt8 DEF_x__h91546;
  tUInt8 DEF_x__h91596;
  tUInt8 DEF_x__h88425;
  tUInt8 DEF_x__h88475;
  tUInt8 DEF_y__h88275;
  tUInt8 DEF_y__h88295;
  tUInt8 DEF_y__h88282;
  tUInt8 DEF_x__h120059;
  tUWide DEF_deq__avValue1;
 
 /* Rules */
 public:
  void RL_first();
  void RL_second();
  void RL_third();
  void RL_last();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkIFFTFolded &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkIFFTFolded &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkIFFTFolded &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkIFFTFolded &backing);
};

#endif /* ifndef __mkIFFTFolded_h__ */
