/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Sat Jun  3 18:09:05 PDT 2017
 * 
 */

/* Generation options: */
#ifndef __mkIFFTFolded_h__
#define __mkIFFTFolded_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkIFFTFolded module */
class MOD_mkIFFTFolded : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_bfly_0;
  MOD_mkBfly4 INST_bfly_1;
  MOD_mkBfly4 INST_bfly_10;
  MOD_mkBfly4 INST_bfly_11;
  MOD_mkBfly4 INST_bfly_12;
  MOD_mkBfly4 INST_bfly_13;
  MOD_mkBfly4 INST_bfly_14;
  MOD_mkBfly4 INST_bfly_15;
  MOD_mkBfly4 INST_bfly_2;
  MOD_mkBfly4 INST_bfly_3;
  MOD_mkBfly4 INST_bfly_4;
  MOD_mkBfly4 INST_bfly_5;
  MOD_mkBfly4 INST_bfly_6;
  MOD_mkBfly4 INST_bfly_7;
  MOD_mkBfly4 INST_bfly_8;
  MOD_mkBfly4 INST_bfly_9;
  MOD_Reg<tUInt8> INST_counter;
  MOD_Fifo<tUWide> INST_f1;
  MOD_Fifo<tUWide> INST_inFIFO;
  MOD_Fifo<tUWide> INST_outFIFO;
 
 /* Constructor */
 public:
  MOD_mkIFFTFolded(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_stage__h83146;
 
 /* Local definitions */
 private:
  tUWide DEF_f1_first____d321;
  tUWide DEF_inFIFO_first____d22;
  tUInt64 DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d323;
  tUInt64 DEF__63_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_0_CONCAT_ETC___d21;
  tUInt64 DEF_bfly_14_bfly4_59_QUOT_2_PLUS_0_CONCAT_counter__ETC___d328;
  tUInt64 DEF__59_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_8_CONCAT_ETC___d38;
  tUInt64 DEF_bfly_13_bfly4_55_QUOT_2_PLUS_0_CONCAT_counter__ETC___d333;
  tUInt64 DEF__55_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_4_CONCAT_ETC___d54;
  tUInt64 DEF_bfly_12_bfly4_51_QUOT_2_PLUS_0_CONCAT_counter__ETC___d338;
  tUInt64 DEF__51_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_0_CONCAT_ETC___d70;
  tUInt64 DEF_bfly_11_bfly4_47_QUOT_2_PLUS_0_CONCAT_counter__ETC___d343;
  tUInt64 DEF__47_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_6_CONCAT_ETC___d86;
  tUInt64 DEF_bfly_10_bfly4_43_QUOT_2_PLUS_0_CONCAT_counter__ETC___d348;
  tUInt64 DEF__43_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_2_CONCAT_ETC___d102;
  tUInt64 DEF_bfly_9_bfly4_39_QUOT_2_PLUS_0_CONCAT_counter_S_ETC___d353;
  tUInt64 DEF__39_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_08_CONCA_ETC___d118;
  tUInt64 DEF_bfly_8_bfly4_35_QUOT_2_PLUS_0_CONCAT_counter_S_ETC___d358;
  tUInt64 DEF__35_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_24_CONCA_ETC___d134;
  tUInt64 DEF_bfly_7_bfly4_31_QUOT_2_PLUS_0_CONCAT_counter_S_ETC___d363;
  tUInt64 DEF__31_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_40_CONCA_ETC___d150;
  tUInt64 DEF_bfly_6_bfly4_27_QUOT_2_PLUS_0_CONCAT_counter_S_ETC___d368;
  tUInt64 DEF__27_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_56_CONCA_ETC___d166;
  tUInt64 DEF_bfly_5_bfly4_23_QUOT_2_PLUS_0_CONCAT_counter_S_ETC___d373;
  tUInt64 DEF__23_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_72_CONCA_ETC___d182;
  tUInt64 DEF_bfly_4_bfly4_19_QUOT_2_PLUS_0_CONCAT_counter_S_ETC___d378;
  tUInt64 DEF__19_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_88_CONCA_ETC___d198;
  tUInt64 DEF_bfly_3_bfly4_15_QUOT_2_PLUS_0_CONCAT_counter_S_ETC___d383;
  tUInt64 DEF__15_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_04_CONCA_ETC___d214;
  tUInt64 DEF_bfly_2_bfly4_11_QUOT_2_PLUS_0_CONCAT_counter_S_ETC___d388;
  tUInt64 DEF__11_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_20_CONCA_ETC___d230;
  tUInt64 DEF_bfly_1_bfly4_7_QUOT_2_PLUS_0_CONCAT_counter_SR_ETC___d393;
  tUInt64 DEF__7_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_36_CONCAT_ETC___d246;
  tUInt64 DEF_bfly_0_bfly4_3_QUOT_2_PLUS_0_CONCAT_counter_SR_ETC___d398;
  tUInt64 DEF__3_QUOT_2_PLUS_0_CONCAT_counter_SRL_6_52_CONCAT_ETC___d262;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d315;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d312;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d449;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d446;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d309;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d443;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d306;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d440;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d303;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d437;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d300;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d434;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d297;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d431;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d294;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d428;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d291;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d425;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d288;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d422;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d285;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d419;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d282;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d416;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d279;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d413;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d276;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d410;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d273;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d407;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d270;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d404;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d267;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d401;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d251;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d396;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d235;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d391;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d219;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d386;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d203;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d381;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d187;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d376;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d171;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d371;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d155;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d366;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d139;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d361;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d123;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d356;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d107;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d351;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d91;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d346;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d75;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d341;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d59;
  tUWide DEF_bfly_15_bfly4_63_QUOT_2_PLUS_0_CONCAT_counter__ETC___d336;
  tUInt8 DEF_x__h113029;
  tUInt8 DEF_x__h113079;
  tUInt8 DEF_x__h111384;
  tUInt8 DEF_x__h111434;
  tUInt8 DEF_x__h109739;
  tUInt8 DEF_x__h109789;
  tUInt8 DEF_x__h108094;
  tUInt8 DEF_x__h108144;
  tUInt8 DEF_x__h106449;
  tUInt8 DEF_x__h106499;
  tUInt8 DEF_x__h104804;
  tUInt8 DEF_x__h104854;
  tUInt8 DEF_x__h103159;
  tUInt8 DEF_x__h103209;
  tUInt8 DEF_x__h101514;
  tUInt8 DEF_x__h101564;
  tUInt8 DEF_x__h99869;
  tUInt8 DEF_x__h99919;
  tUInt8 DEF_x__h98224;
  tUInt8 DEF_x__h98274;
  tUInt8 DEF_x__h96579;
  tUInt8 DEF_x__h96629;
  tUInt8 DEF_x__h94934;
  tUInt8 DEF_x__h94984;
  tUInt8 DEF_x__h93289;
  tUInt8 DEF_x__h93339;
  tUInt8 DEF_x__h91644;
  tUInt8 DEF_x__h91694;
  tUInt8 DEF_x__h89999;
  tUInt8 DEF_x__h90049;
  tUInt8 DEF_x__h88354;
  tUInt8 DEF_x__h88404;
  tUInt8 DEF_x__h112525;
  tUInt8 DEF_x__h112806;
  tUInt8 DEF_x__h112847;
  tUInt8 DEF_x__h112897;
  tUInt8 DEF_x__h110880;
  tUInt8 DEF_x__h111161;
  tUInt8 DEF_x__h111202;
  tUInt8 DEF_x__h111252;
  tUInt8 DEF_x__h109235;
  tUInt8 DEF_x__h109516;
  tUInt8 DEF_x__h109557;
  tUInt8 DEF_x__h109607;
  tUInt8 DEF_x__h107590;
  tUInt8 DEF_x__h107871;
  tUInt8 DEF_x__h107912;
  tUInt8 DEF_x__h107962;
  tUInt8 DEF_x__h105945;
  tUInt8 DEF_x__h106226;
  tUInt8 DEF_x__h106267;
  tUInt8 DEF_x__h106317;
  tUInt8 DEF_x__h104300;
  tUInt8 DEF_x__h104581;
  tUInt8 DEF_x__h104622;
  tUInt8 DEF_x__h104672;
  tUInt8 DEF_x__h102655;
  tUInt8 DEF_x__h102936;
  tUInt8 DEF_x__h102977;
  tUInt8 DEF_x__h103027;
  tUInt8 DEF_x__h101010;
  tUInt8 DEF_x__h101291;
  tUInt8 DEF_x__h101332;
  tUInt8 DEF_x__h101382;
  tUInt8 DEF_x__h99365;
  tUInt8 DEF_x__h99646;
  tUInt8 DEF_x__h99687;
  tUInt8 DEF_x__h99737;
  tUInt8 DEF_x__h97720;
  tUInt8 DEF_x__h98001;
  tUInt8 DEF_x__h98042;
  tUInt8 DEF_x__h98092;
  tUInt8 DEF_x__h96075;
  tUInt8 DEF_x__h96356;
  tUInt8 DEF_x__h96397;
  tUInt8 DEF_x__h96447;
  tUInt8 DEF_x__h94430;
  tUInt8 DEF_x__h94711;
  tUInt8 DEF_x__h94752;
  tUInt8 DEF_x__h94802;
  tUInt8 DEF_x__h92785;
  tUInt8 DEF_x__h93066;
  tUInt8 DEF_x__h93107;
  tUInt8 DEF_x__h93157;
  tUInt8 DEF_x__h91140;
  tUInt8 DEF_x__h91421;
  tUInt8 DEF_x__h91462;
  tUInt8 DEF_x__h91512;
  tUInt8 DEF_x__h89495;
  tUInt8 DEF_x__h89776;
  tUInt8 DEF_x__h89817;
  tUInt8 DEF_x__h89867;
  tUInt8 DEF_x__h87850;
  tUInt8 DEF_x__h88131;
  tUInt8 DEF_x__h88172;
  tUInt8 DEF_x__h88222;
  tUInt8 DEF_x__h112938;
  tUInt8 DEF_x__h112988;
  tUInt8 DEF_x__h111293;
  tUInt8 DEF_x__h111343;
  tUInt8 DEF_x__h109648;
  tUInt8 DEF_x__h109698;
  tUInt8 DEF_x__h108003;
  tUInt8 DEF_x__h108053;
  tUInt8 DEF_x__h106358;
  tUInt8 DEF_x__h106408;
  tUInt8 DEF_x__h104713;
  tUInt8 DEF_x__h104763;
  tUInt8 DEF_x__h103068;
  tUInt8 DEF_x__h103118;
  tUInt8 DEF_x__h101423;
  tUInt8 DEF_x__h101473;
  tUInt8 DEF_x__h99778;
  tUInt8 DEF_x__h99828;
  tUInt8 DEF_x__h98133;
  tUInt8 DEF_x__h98183;
  tUInt8 DEF_x__h96488;
  tUInt8 DEF_x__h96538;
  tUInt8 DEF_x__h94843;
  tUInt8 DEF_x__h94893;
  tUInt8 DEF_x__h93198;
  tUInt8 DEF_x__h93248;
  tUInt8 DEF_x__h91553;
  tUInt8 DEF_x__h91603;
  tUInt8 DEF_x__h89908;
  tUInt8 DEF_x__h89958;
  tUInt8 DEF_x__h88263;
  tUInt8 DEF_x__h88313;
  tUInt8 DEF_y__h88113;
  tUInt8 DEF_y__h88133;
  tUInt8 DEF_y__h88120;
  tUInt8 DEF_x__h80656;
  tUWide DEF_deq__avValue1;
 
 /* Rules */
 public:
  void RL_first();
  void RL_second();
  void RL_third();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkIFFTFolded &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkIFFTFolded &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkIFFTFolded &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkIFFTFolded &backing);
};

#endif /* ifndef __mkIFFTFolded_h__ */
